### ISSUE TITLE
I suggest to rename this module in package.json from `ncu` to another name to avoid conflict with ncu aka `npm-check-updates`

### ISSUE THREAD

**Issue by alundiak** [ncu-weather/ncu-weather-cli#2]
@Jon007 spotted on the fact of existing another `ncu` - he created issue: https://github.com/tjunnone/npm-check-updates/issues/135
 I'm not sure what he meant under "user error"? 

But what I may see, that alias `ncu` from `npm-check-updates` might be so get used and misused as I explain below:

I did mistakenly: knowing that `ncu` is alias of `npm-check-updates`, I thought I can install/update existed module, also using that alias.

```
npm install ncu -g              
npm WARN gentlyRm not removing /usr/local/bin/ncu as it wasn't installed by /usr/local/lib/node_modules/ncu
/usr/local/bin/ncu -> /usr/local/lib/node_modules/ncu/cli.js
/usr/local/lib
└── ncu@0.2.0 
```

```
ncu --version                   
NCU Real Time Weather is Running......
2017/5/1 0:10 Monday UTC+8:00

Apparent Temperature: 20.5 ℃
         Temperature: 19.7 ℃
              PRECIP: 0 mm/hr


(σ′▽‵)′▽‵)σ
```

I spotted/realized this when wanted to check version :) And realized, `ncu is not ncu anymore` :)

So I found this issue (https://github.com/tjunnone/npm-check-updates/issues/135) over the Internet, and realized, that I might have installed another nodeJS module, and installed `npm-check-updates` again:

```
npm install -g npm-check-updates
npm WARN gentlyRm not removing /usr/local/bin/ncu as it wasn't installed by /usr/local/lib/node_modules/npm-check-updates
/usr/local/bin/npm-check-updates -> /usr/local/lib/node_modules/npm-check-updates/bin/npm-check-updates
/usr/local/bin/ncu -> /usr/local/lib/node_modules/npm-check-updates/bin/ncu
/usr/local/lib
└─┬ npm-check-updates@2.11.0 
  └─┬ snyk@1.29.0
    ├─┬ configstore@1.4.0
    │ └── write-file-atomic@1.3.4 
    ├── debug@2.6.6 
    ├─┬ request@2.81.0
    │ ├── extend@3.0.1 
    │ ├─┬ har-validator@4.2.1
    │ │ └── ajv@4.11.8 
    │ └─┬ http-signature@1.1.1
    │   └─┬ sshpk@1.13.0
    │     └── getpass@0.1.7 
    └─┬ snyk-config@1.0.1
      └─┬ nconf@0.7.2
        └─┬ yargs@3.15.0
          └─┬ cliui@2.1.0
            └─┬ center-align@0.1.3
              └─┬ align-text@0.1.4
                └── kind-of@3.2.0 

```
```
ncu --version
2.11.0
```

Meaning, that after fresh installation, `npm-check-updates` replace valid MacOS command 'ncu' by its own `ncu` alias.

I mean, that it's conflict of Unix command names/aliases.
**Imagine, I want to use both commands?** I will not be able to do this. !!!

As far as I see, https://www.npmjs.com/package/ncu aka https://github.com/ncu-weather/ncu-weather-cli has first commit Feb-27-2017 and first commit of https://github.com/tjunnone/npm-check-updates/ is far beyond older.

cc/  @raineorshine @tjunnone

**Comment by raineorshine** [comment]
What about manually adding an alternative alias in your bashrc?

e.g.

```
alias nnn="/usr/local/lib/node_modules/ncu-weather-cli/cli.js"
```

**Comment by lovenery** [comment]
WOW! I never thought it cause this problem until see this issue...

Because `NCU(National Central University)` is my school's name, I simply named it `ncu` at that time.

As far as I know, if I unpublish or rename this module, old version will still be available by `npm install ncu` until someone create new `ncu` version. I think the best way is that the npm company implements module namespace, just like php dependency management, `Composer`(https://packagist.org/explore), and then nobody will install wrong module. 

Finally, I will not rename this module, but I will add another alias in package.json which can let two project do its job in the same time. 

I'm still a beginner, maybe your suggestion is right. Sorry about it.

**Comment by alundiak** [comment]
@raineorshine I know and would do your suggested way, but I treat this rather as workaround, I would use when end of world, and it depends on people's life :) But now, it's simply matter of correct modules names in NPM space. Me, as a consumer, I don't want to do some workaround to use both modules. 


@lovenery 
This is my very test/dummy module [`feby`](https://www.npmjs.com/package/feby)  which was time ago named as `test` and after I realized it conflicted with another [`test`](https://www.npmjs.com/package/test) module (which is also btw, not correctly published). In fact I was latter/latest/on-top, so I miss-replaced that test module, sure my fault). And then I simply `npm unpublish test` from my local codebase (u may also try `deprecate` first, so that new downloads would would be notified) all old versions, and re-published new version (so that new downloads/install will be possible to only this named module). Then I renamed `name` in my `package.json` ("test" => "feby") and published new version/release of my module. This versioning is despite git tags on github, it's not related (meaning it's not necessary to be the same, version of module in npm registry defined by `package.json`:`version`).
- https://docs.npmjs.com/cli/unpublish
- https://docs.npmjs.com/cli/deprecate

For the sake of study/knowledge, @lovenery here is urls to my closed issues for NPM Registry web site: 
- https://github.com/npm/www/issues/127
- https://github.com/npm/www/issues/128

@raineorshine u know, I will uninstall original `ncu` module, because I don't need it, so I may still use ncu as alias for npm-check-updates. But again, for the sake of NPM registry clear and transparent settings and for the sake of modules names and aliases, I would kindly recommend to figure out something here :) 

@lovenery 
> module namespace

I think it will not help, because as a end consumer of your ncu, when I install, I will replace ncu alias I already have. So the issue starts on Unix level, after module installation.
Ideally, would be eliminate alias at all, and leave ONLY `ncu-weather-cli` and `npm-check-updates` as executable commands for Unix/Shell.But I guess u both will not like to do this :) 


Anyway, don't get me wrong, I just a consumer of node modules, and I spotted on this issue recently, and it's in fact not a big deal... :)

**Comment by raineorshine** [comment]
These are all good points. The fact that npm prevents naming conflicts and the module level but not at the binary level means that there is nothing preventing modules from having different binary names and thus creating the possibility of conflict.

Sticking with the exact npm module name for the binary executive is the conservative and rational approach! I added `ncu` as an alias for `npm-check-updates` because people complained about the length of the name and didn't want to add an alias at the shell level. You should still be able to run `npm-check-updates` with the full name as well.

In a perfect world npm would provide a more intuitive process of not overwriting conflicting binaries and instead prompting for an alternative name.

My guess is that this issue affects a very small number of users. Lucky you! :). Thanks for your thoughtful response.

**Comment by vdh** [comment]
I don't think `ncu` is really a good CLI name for a script that checks the weather from National Central University. Generally the script name should be a product name or an action. E.g. when I run `ncu`, I am executing `npm-check-updates`. It doesn't make sense to be executing "National Central University" as a concept.

`ncu-weather` or some other variation would be more appropriate of a context for the script's name.

**Comment by lovenery** [comment]
@vdh Yeah. I agree with you.

To make everyone's life easier, I took some time to try finding the solution to removing the npm repo. I found that I could not do `npm unpublish ncu --force`... cause it doesn't meet the rule - `had less than 300 downloads over the last week`. Please refer to https://www.npmjs.com/policies/unpublish.

Should I deprecate it and transfer the ownership to npmjs account by doing `npm deprecate <package> "<message>"` if I don't want people to be misled again? Or Is there any way to solve it?

**Comment by raineorshine** [comment]
You could deprecate `ncu` and publish as a new package `ncu-weather` with binary `ncu-weather`.

It would be a good idea to confirm that doing so actually removes `ncu` from the user's `PATH` when they upgrade though.

**Comment by raineorshine** [comment]
For some historical background, I added the `ncu` alias to `npm-check-updates` [on April 3rd, 2015](https://github.com/raineorshine/npm-check-updates/commit/b3be8900ae3b83232a22afbc3459145065a0f9b7) due to user demand. I didn't think to publish it to `ncu` on the registry at the time. `ncu` (weather) was published on February 27, 2017.

It's a relatively small subset of users that install both, but it's confusing nonetheless :).

**Comment by lovenery** [comment]
@raineorshine
Thank you for your advice.
I have deprecated the old package and rename it. 
Have a nice day!

**Comment by passariello** [comment]
I am incurred in same issue some days ago! .. just let you know... the error persist

**Comment by lovenery** [comment]
@passariello, I know the issue remains...
The reason is that I cannot `npm unpublish <package_name> --force`, see https://docs.npmjs.com/policies/unpublish#packages-published-more-than-72-hours-ago

**Comment by lk77** [comment]
I had the issue today, just did npx ncu and it did install this package, glad to see it's not malicious at least

**Comment by alundiak** [comment]
@lovenery @raineorshine I see that the issue still relevant even in Oct 2023 :) So I wasn't only one missled, confused "consumer" after all.
